# **Laboratory Task 5**
---

## **DS413 | Deep Learning**
### **PyTorch Exercise**

<div style="text-align: justify;">
This task is designed to develop familiarity with random number generation, tensor manipulation, and basic linear algebra operations in PyTorch while ensuring reproducibility through seed setting. The task guides the learner through creating arrays and tensors, adjusting data types, reshaping, slicing, applying mathematical operations without altering the original data, and finally performing a valid matrix multiplication. The overall objective is to strengthen understanding of how NumPy and PyTorch integrate in managing data structures, controlling randomness, and carrying out fundamental tensor computations.
    <br>
    
</div>

<div style="width: 80%; margin: 0 auto;">
    <div style="border: 6px solid #4F6D38; padding: 15px; background-color: transparent; border-radius: 5px; text-align: left;">
    <h3><strong>Laboratory Task 5</strong></h3>
        
<strong>1. Perform Standard Imports</strong>    


<strong>2. Create a function called set_seed() that accepts seed: int as a parameter, this function must return nothing but just set the seed to a certain value.</strong>


<strong>3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive), call the set_seed() function and use 42 as the seed parameter.</strong>


<strong>4. Create a tensor "x" from the array above</strong>


<strong>5. Change the dtype of x from int32 to int64</strong>


<strong>6. Reshape x into a 3x2 tensor</strong>
There are several ways to do this.


<strong>7. Return the right-hand column of tensor x</strong>

<strong>8. Without changing x, return a tensor of square values of x</strong>
There are several ways to do this.

<strong>9. Create a tensor y with the same number of elements as x, that can be matrix-multiplied with x</strong>
Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive). Use 42 as seed.
Think about what shape it should have to permit matrix multiplication.

<strong>10. Find the matrix product of x and y.  </strong>10. Find the matrix product of x and y.
        
   </div>
</div>

#### 1. Perform Standard Imports

In [1]:
import numpy as np
import torch
import sys

#### 2. Create a function called set_seed() that accepts seed: int as a parameter, this function must return nothing but just set the seed to a certain value.

In [2]:
def set_seed(seed: int):
    np.random.seed(seed)
    torch.manual_seed(seed)

#### 3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive), call the set_seed() function and use 42 as the seed parameter.


In [3]:
set_seed(42)

arr = np.random.randint(0, 5, size = 6)
print(arr)

[3 4 2 4 4 1]


#### 4. Create a tensor "x" from the array above

In [4]:
x = torch.tensor(arr)

In [5]:
print(x)

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)


#### 5. Change the dtype of x from int32 to int64

In [7]:
x = x.to(torch.int64)

print(x.dtype)

torch.int64


#### 6. Reshape x into a 3x2 tensor

In [8]:
x = x.view(3, 2)
x

tensor([[3, 4],
        [2, 4],
        [4, 1]])

#### 7. Return the right-hand column of tensor x

In [9]:
right = x[:, 1]
print(right)

tensor([4, 4, 1])


#### 8. Without changing x, return a tensor of square values of x

In [10]:
squared = x**2
print(squared)

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])


#### 9. Create a tensor y with the same number of elements as x, that can be matrix-multiplied with x

In [11]:
set_seed(42)
y = torch.randint(0,5, (2, 3))
print(y)

tensor([[2, 2, 1],
        [4, 1, 0]])


#### 10. Find the matrix product of x and y.

In [12]:
prod = torch.matmul(x,y)
print(prod)

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])
